clear L
deg = pi/180;

L(1) = Revolute('d', 1, 'a', 0, 'alpha', pi/2, ...
    'I', [0, 0, 0], ...
    'm', 0, ...
    'Jm', 10^-4, ...
    'G', 500, ...
    'B', 10*10^-4, ...
    'qlim', [-180 180]*deg );

L(2) = Revolute('d', 0, 'a', 1, 'alpha', 0, ...
    'I', [0.0125, 0.84, 0.84], ...
    'm', 10, ...
    'Jm', 10^-4, ...
    'G', 500, ...
    'B', 10*10^-4, ...
    'qlim', [-90 90]*deg );


L(3) = Revolute('d', 0, 'a', 1, 'alpha', 0,  ...
    'I', [0.0125, 0.84, 0.84], ...
    'm', 10, ...
    'Jm', 10^-4, ...
    'G', 500, ...
    'B', 10*10^-4, ...
    'qlim', [-90 90]*deg );

 PlanarRob = SerialLink(L, 'name', 'PlanarRob');

holdPos= [0 0 0 ];
homePos = [0 0 -pi/2];
PlanarRob.payload(1, [0 0 0]);
torqueHomePos = PlanarRob.gravload(homePos, [0 0 1]);
torqueHoldPos = PlanarRob.gravload(holdPos, [0 0 1]);

%%PlanarRob.plot(qz);
%%PlanarRob.teach();
clear L


%%We know that T = distance*Force*sin(Theta)
%%in first case (home position): angle theta between Force and distance
%%from joint3 to end effector is 0, also torque on joint2 will decrease
%%in second case(hold position): angle theta between in both joints 90 deg
%%therefore T = L2*F for joint3 and T = (L1+L2)*F for joint2
